### ISSUE TITLE
Buy or rent crank stands

### ISSUE THREAD

**Issue by burlexpo** [burlexpo/gbe10#17]
Can you take a look at the "ST-B2" model on http://www.lighttruss.cn/elevatortower.htm and tell me what you think? I can get six of them for about $1400 (including freight).  I'll bug High Output about a price for rentals, but I want to see if these will even suit our purposes or I should get a quote on one of the heavier duty models.

**Comment by SRWILHELM** [comment]
the "ST-C2" is what i would prefer but the "ST-C1" Might be enough. The "B" ones are not designed to lift truss.

the info on the sight feels a bit lacking but they claim to make stuff to an acceptable standard.

**Comment by burlexpo** [comment]
I just saw a pair of these on Craiglist for $150 each which is a gret price -- if they work for us.  Do they?
http://globaltruss.com/ProductDetails.aspx?ItemNumber=227&MainId=4&Category=41

I certainly think they'd work for the backdrop.
